// <auto-generated />
using System;
using Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Domain.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea5028d1-3bdb-41b2-9141-fc6329d89a8b"),
                            Description = "Canal dedidaco a dot net",
                            Name = "DotNetCore"
                        },
                        new
                        {
                            Id = new Guid("da2109e3-df69-4bd3-9b1f-eab157f77052"),
                            Description = "Canal dedidaco a Minecraft",
                            Name = "Minecraft"
                        },
                        new
                        {
                            Id = new Guid("14cf2484-45c3-4981-8144-b400e31b377d"),
                            Description = "Canal dedidaco a React Js",
                            Name = "React Js"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
